import cv2
from enum import Enum


class CvEnums(Enum):
    K_RECTANGLE = cv2.MORPH_RECT
    K_ELLIPSE = cv2.MORPH_ELLIPSE
    K_CROSS = cv2.MORPH_CROSS
    MORPH_OPEN = cv2.MORPH_OPEN
    MORPH_CLOSE = cv2.MORPH_CLOSE
    MORPH_GRADIENT = cv2.MORPH_GRADIENT
    MORPH_TOPHAT = cv2.MORPH_TOPHAT
    MORPH_BLACKHAT = cv2.MORPH_BLACKHAT
    MORPH_ERODE = cv2.MORPH_ERODE
    MORPH_DILATE = cv2.MORPH_DILATE
    THRESH_GAUSSIAN = cv2.ADAPTIVE_THRESH_GAUSSIAN_C
    THRESH_MEAN = cv2.ADAPTIVE_THRESH_MEAN_C
    THRESH_BINARY = cv2.THRESH_BINARY
    THRESH_INV = cv2.THRESH_BINARY_INV
    THRESH_TRUNC = cv2.THRESH_TRUNC
    COLOUR_RED = (0, 0, 255)
    COLOUR_BLUE = (255, 0, 0)
    COLOUR_GREEN = (0, 255, 0)
    COLOUR_WHITE = (255, 255, 255)
    COLOUR_BLACK = (0, 0, 0)
    MAT_INTER_AREA = cv2.INTER_AREA
    MAT_INTER_CUBIC = cv2.INTER_CUBIC
    MAT_INTER_LINEAR = cv2.INTER_LINEAR
    MAT_WARP_INVERSE_MAP = cv2.WARP_INVERSE_MAP
    BORDER_REPLICATE = cv2.BORDER_REPLICATE
    BORDER_CONSTANT = cv2.BORDER_CONSTANT
    RETR_LIST = cv2.RETR_LIST
    RETR_EXTERNAL = cv2.RETR_EXTERNAL
    RETR_TREE = cv2.RETR_TREE
    CHAIN_APPROX_SIMPLE = cv2.CHAIN_APPROX_SIMPLE
    CHAIN_APPROX_NONE = cv2.CHAIN_APPROX_NONE
    CHAIN_APPROX_TC89_KCOS = cv2.CHAIN_APPROX_TC89_KCOS
    NORM_MINMAX = cv2.NORM_MINMAX
    CV_8UC1 = cv2.CV_8UC1
